/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    403: (typeof import("./src/components/ErrorMsgPage/403.vue"))["default"];
    404: (typeof import("./src/components/ErrorMsgPage/404.vue"))["default"];
    500: (typeof import("./src/components/ErrorMsgPage/500.vue"))["default"];
    CommonDialog: (typeof import("@/components/Dialog/index.vue"))["default"];
    Dialog: (typeof import("./src/components/Dialog/index.vue"))["default"];
    Drawer: (typeof import("@/components/Drawer/index.vue"))["default"];
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElConfigProvider: (typeof import("element-plus/es"))["ElConfigProvider"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElPagination: (typeof import("element-plus/es"))["ElPagination"];
    ElPopover: (typeof import("element-plus/es"))["ElPopover"];
    ElRadio: (typeof import("element-plus/es"))["ElRadio"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ErrorMsgPage: (typeof import("./src/components/ErrorMsgPage/index.vue"))["default"];
    Layout: (typeof import("./src/components/Layout/index.vue"))["default"];
    LeftAsideMenu: (typeof import("./src/components/Layout/components/LeftAsideMenu.vue"))["default"];
    Loading: (typeof import("./src/components/Loading/index.vue"))["default"];
    PageHeader: (typeof import("./src/components/Layout/components/PageHeader.vue"))["default"];
    PaginationCmp: (typeof import("./src/components/ProTable/components/PaginationCmp.vue"))["default"];
    ProTable: (typeof import("./src/components/ProTable/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SvgIcon: (typeof import("./src/components/SvgIcon/index.vue"))["default"];
    Table: (typeof import("@/components/ProTable/index.vue"))["default"];
    TableColumn: (typeof import("./src/components/ProTable/components/TableColumn.vue"))["default"];
  }
}
